name: Realyt
version: '${project.version}'
main: com.realyt.realyt.Realyt
api-version: '1.20'
commands:
  putrandom:
    description: "Colocar aleatóriamente os elementos"
    usage: "/<command>"
    aliases:
      - pr
  putplayer:
    description: "Colocar aleatóriamente os elementos"
    usage: "/<command> player type"
